Repository Rebilly/rebilly-recomponents, pull requests merged in 2019-11, with the labels that each got.

#61 fix(r-input): update r-input as it's updated in recomm again
  packages/recomponents/src/components/r-input/r-input.md
  packages/recomponents/src/components/r-input/r-input.scss
  packages/recomponents/src/components/r-input/r-input.story.js
  packages/recomponents/src/components/r-input/r-input.vue
Labels: task

#59 Tests improve coverage
  packages/recomponents/src/components/r-badge/r-badge.spec.js
  packages/recomponents/src/components/r-badge/r-badge.vue
  packages/recomponents/src/components/r-button/r-button.spec.js
  packages/recomponents/src/components/r-button/r-button.vue
  packages/recomponents/src/components/r-checkbox/r-checkbox.spec.js
  packages/recomponents/src/components/r-checkbox/r-checkbox.vue
  packages/recomponents/src/components/r-date-input/__snapshots__/r-date-input.spec.js.snap
  packages/recomponents/src/components/r-date-input/r-calendar-manager.spec.js
  packages/recomponents/src/components/r-date-input/r-calendar-manager.vue
  packages/recomponents/src/components/r-date-input/r-date-input.spec.js
  packages/recomponents/src/components/r-date-input/r-date-input.vue
  packages/recomponents/src/components/r-icon-button/__snapshots__/r-icon-button.spec.js.snap
  packages/recomponents/src/components/r-icon-button/r-icon-button.spec.js
  packages/recomponents/src/components/r-img/__snapshots__/r-img.spec.js.snap
  packages/recomponents/src/components/r-img/r-img.spec.js
  packages/recomponents/src/components/r-input/r-input.spec.js
  packages/recomponents/src/components/r-input/r-input.vue
  packages/recomponents/src/components/r-loader/r-loader.vue
  packages/recomponents/src/components/r-modal/r-modal.vue
  packages/recomponents/src/components/r-pagination/__snapshots__/r-pagination-control.spec.js.snap
  packages/recomponents/src/components/r-pagination/r-pagination-control.spec.js
  packages/recomponents/src/components/r-pagination/r-pagination-control.vue
  packages/recomponents/src/components/r-pagination/r-pagination.spec.js
  packages/recomponents/src/components/r-pagination/r-pagination.vue
  packages/recomponents/src/components/r-popper/r-popper.spec.js
  packages/recomponents/src/components/r-popper/r-popper.vue
  packages/recomponents/src/components/r-radio/r-radio.spec.js
  packages/recomponents/src/directives/r-click-outside/r-click-outside.js
  packages/recomponents/src/directives/r-click-outside/r-click-outside.spec.js
  packages/recomponents/src/directives/r-content/r-content.spec.js
  packages/recomponents/src/directives/r-tooltip/r-tooltip.js
  packages/recomponents/src/directives/r-tooltip/r-tooltip.spec.js
  packages/recomponents/src/directives/r-tooltip/r-tooltip.story.js
Labels: task

#62 fix(RBadge): Add default class to RBadge
  packages/recomponents/src/components/r-badge/r-badge.scss
  packages/recomponents/src/components/r-badge/r-badge.spec.js
  packages/recomponents/src/components/r-badge/r-badge.vue
Labels: bug

#63 Fix invalid state of RInput
  packages/recomponents/src/components/r-input/r-input.spec.js
  packages/recomponents/src/components/r-input/r-input.story.js
  packages/recomponents/src/components/r-input/r-input.vue
  packages/recomponents/src/styles/theme.scss
Labels: bug

#66 fix(rtabs): include the value field in the payload of 'tab-select'
  packages/recomponents/src/components/r-tabs/r-tabs.vue
Labels: awaiting review

#65 Updating RCheckbox method name and adding comments
  packages/recomponents/src/components/r-checkbox/r-checkbox.vue
Labels: chore

#67 Upgrade storybook
  packages/recomponents/package.json
Labels: task

#68 Fix empty select jumping
  packages/recomponents/src/components/r-select/r-select.scss
  packages/recomponents/src/components/r-select/r-select.story.js
  packages/recomponents/src/styles/theme.scss
  packages/recomponents/yarn.lock
Labels: awaiting review, bug

#71 Add alias for SASS
  packages/recomponents/.storybook/webpack.config.js
  packages/recomponents/vue.config.js
Labels: awaiting review, chore

#73 fix(component): Fix icons in IE 11
  packages/recomponents/src/components/r-icon/r-icon.vue
Labels: awaiting review, bug

#75 Fix eslint errors
  packages/recomponents/src/components/r-badge/r-badge.story.js
  packages/recomponents/src/components/r-select/r-select.spec.js
  packages/recomponents/src/components/r-select/r-select.vue
Labels: awaiting review, chore

#72 Remove i18n dependency
  packages/recomponents/.storybook/config.js
  packages/recomponents/package.json
  packages/recomponents/src/components/r-button/r-button.spec.js
  packages/recomponents/src/components/r-button/r-button.vue
  packages/recomponents/src/components/r-checkbox/r-checkbox.spec.js
  packages/recomponents/src/components/r-checkbox/r-checkbox.vue
  packages/recomponents/src/components/r-date-input/r-date-input.spec.js
  packages/recomponents/src/components/r-modal/r-modal.spec.js
  packages/recomponents/src/components/r-pagination/__snapshots__/r-pagination-control.spec.js.snap
  packages/recomponents/src/components/r-pagination/__snapshots__/r-pagination.spec.js.snap
  packages/recomponents/src/components/r-pagination/r-pagination-control.spec.js
  packages/recomponents/src/components/r-pagination/r-pagination.spec.js
  packages/recomponents/src/components/r-popper/r-popper.spec.js
  packages/recomponents/src/components/r-radio/r-radio.spec.js
  packages/recomponents/src/components/r-select/__snapshots__/r-select.spec.js.snap
  packages/recomponents/src/components/r-select/r-select.spec.js
  packages/recomponents/src/components/r-select/r-select.vue
  packages/recomponents/src/index.js
  packages/recomponents/yarn.lock
Labels: bug

#74 Update readme with tutorial how to follow commit convention
  README.md
Labels: awaiting review, chore

#76 Updated RSelect styles
  packages/recomponents/src/components/r-select/r-select.scss
  packages/recomponents/src/styles/theme.scss
Labels: bug

#77 Fix package.json to run script subcommands sequentially
  packages/recomponents/package.json
  packages/recomponents/src/components/r-radio/r-radio.spec.js
Labels: chore

#57 Add missed data types and value to RRadio
  packages/recomponents/src/components/r-input/r-input.scss
  packages/recomponents/src/components/r-radio/__snapshots__/r-radio.spec.js.snap
  packages/recomponents/src/components/r-radio/r-radio.spec.js
  packages/recomponents/src/components/r-radio/r-radio.story.js
  packages/recomponents/src/components/r-radio/r-radio.vue
  packages/recomponents/src/styles/theme.scss
Labels: task

#83 Revert storybook version to fix bug with knobs
  packages/recomponents/package.json
  packages/recomponents/yarn.lock
Labels: bug, chore

#70 Make tabs accessible by default
  packages/recomponents/src/components/r-tabs/__snapshots__/r-tabs.spec.js.snap
  packages/recomponents/src/components/r-tabs/r-tab.vue
  packages/recomponents/src/components/r-tabs/r-tabs.scss
  packages/recomponents/src/components/r-tabs/r-tabs.spec.js
  packages/recomponents/src/components/r-tabs/r-tabs.story.js
  packages/recomponents/src/components/r-tabs/r-tabs.vue
  packages/recomponents/src/styles/mixins.scss
Labels: awaiting review, task

#84 fix(RInput): Fix undefined exception
  packages/recomponents/src/components/r-input/r-input.vue
Labels: bug, chore

#85 fix(r-select): Fix some functionality of r-select component
  packages/recomponents/src/components/r-select/__snapshots__/r-select.spec.js.snap
  packages/recomponents/src/components/r-select/r-select.scss
  packages/recomponents/src/components/r-select/r-select.spec.js
  packages/recomponents/src/components/r-select/r-select.vue
  packages/recomponents/src/styles/theme.scss
Labels: awaiting review, bug

#82 fix(style): Avoid duplicate SCSS
  packages/recomponents/src/components/r-checkbox/r-checkbox.scss
  packages/recomponents/src/components/r-checkbox/r-checkbox.vue
  packages/recomponents/src/components/r-radio/r-radio.scss
  packages/recomponents/src/components/r-radio/r-radio.vue
  packages/recomponents/src/components/r-radio/r-toggle.scss
  packages/recomponents/src/styles/theme.scss
Labels: bug

#87 fix(r-select): Align close icon in r-select tag badges
  packages/recomponents/src/components/r-select/r-select.scss
Labels: bug

#88 Refactor npm scripts
  .gitignore
  docs/3.58a01e9e351b7a618068.bundle.js
  docs/favicon.ico
  docs/iframe.html
  docs/index.html
  docs/main.2c8550724cb84eff4c81.bundle.js
  docs/main.2c8550724cb84eff4c81.bundle.js.map
  docs/main.ff8ad30e0a37444f7f6d.bundle.js
  docs/runtime~main.2c8550724cb84eff4c81.bundle.js
  docs/runtime~main.2c8550724cb84eff4c81.bundle.js.map
  docs/runtime~main.a90268c17dde86687a73.bundle.js
  docs/sb_dll/storybook_ui-manifest.json
  docs/sb_dll/storybook_ui_dll.LICENCE
  docs/sb_dll/storybook_ui_dll.js
  docs/vendors~main.18832f255322f1bf8ee4.bundle.js
  docs/vendors~main.2c8550724cb84eff4c81.bundle.js
  docs/vendors~main.2c8550724cb84eff4c81.bundle.js.map
  packages/recomponents/.storybook/webpack.config.js
  packages/recomponents/babel.config.js
  packages/recomponents/package.json
  packages/recomponents/src/components/r-select/r-select.vue
  packages/recomponents/vue.config.js
  packages/recomponents/yarn.lock
Labels: awaiting review, chore

#91 fix(r-select): null value fix
  packages/recomponents/src/components/r-select/r-select.story.js
  packages/recomponents/src/components/r-select/r-select.vue
Labels: bug
