Repository Rebilly/rebilly-recomponents, pull requests merged in 2019-09, with the labels that each got.

#21 Before release
  packages/recomponents/README.md
  packages/recomponents/src/components/r-badge/r-badge.md
  packages/recomponents/src/components/r-badge/r-badge.vue
  packages/recomponents/src/components/r-button/r-button.md
  packages/recomponents/src/components/r-button/r-button.vue
  packages/recomponents/src/components/r-checkbox/r-checkbox.md
  packages/recomponents/src/components/r-checkbox/r-checkbox.vue
  packages/recomponents/src/components/r-dropdown/r-dropdown.md
  packages/recomponents/src/components/r-dropdown/r-dropdown.vue
  packages/recomponents/src/components/r-icon-button/r-icon-button.md
  packages/recomponents/src/components/r-icon-button/r-icon-button.vue
  packages/recomponents/src/components/r-icon/r-icon.md
  packages/recomponents/src/components/r-icon/r-icon.vue
  packages/recomponents/src/components/r-img/r-img.scss
  packages/recomponents/src/components/r-img/r-img.vue
  packages/recomponents/src/components/r-input/r-input.md
  packages/recomponents/src/components/r-input/r-input.vue
  packages/recomponents/src/components/r-loader/__snapshots__/r-loader.spec.js.snap
  packages/recomponents/src/components/r-loader/r-loader.md
  packages/recomponents/src/components/r-loader/r-loader.scss
  packages/recomponents/src/components/r-loader/r-loader.spec.js
  packages/recomponents/src/components/r-loader/r-loader.vue
  packages/recomponents/src/components/r-radio/r-radio.vue
  packages/recomponents/src/components/r-tile/__snapshots__/r-tile.spec.js.snap
  packages/recomponents/src/components/r-tile/r-tile.md
  packages/recomponents/src/components/r-tile/r-tile.spec.js
  packages/recomponents/src/components/r-tile/r-tile.vue
  packages/recomponents/src/index.js
  packages/recomponents/src/stories/payment-form.story.js
Labels: awaiting review

#24 docs(readme): update example in main readme
  packages/recomponents/README.md
Labels: bug

#25 fix(style): Update checkbox styles and markup
  packages/recomponents/src/components/r-checkbox/__snapshots__/r-checkbox.spec.js.snap
  packages/recomponents/src/components/r-checkbox/r-checkbox.scss
  packages/recomponents/src/components/r-checkbox/r-checkbox.vue
Labels: bug

#23 fix(r-icon): load sprite only once
  packages/recomponents/src/components/r-checkbox/__snapshots__/r-checkbox.spec.js.snap
  packages/recomponents/src/components/r-icon/r-icon-sprites.js
  packages/recomponents/src/components/r-icon/r-icon.vue
Labels: bug

#31 fix(r-icon): RButton loading state doesn't work
  packages/recomponents/src/components/r-button/r-button.story.js
  packages/recomponents/src/components/r-button/r-button.vue
  packages/recomponents/src/components/r-icon/r-icon.scss
Labels: bug

#27 Refactor components styles
  packages/recomponents/src/components/r-badge/r-badge.scss
  packages/recomponents/src/components/r-button/r-button.scss
  packages/recomponents/src/components/r-button/r-button.spec.js
  packages/recomponents/src/components/r-button/r-button.story.js
  packages/recomponents/src/components/r-button/r-button.vue
  packages/recomponents/src/components/r-checkbox/r-checkbox.scss
  packages/recomponents/src/components/r-dropdown/r-dropdown.scss
  packages/recomponents/src/components/r-icon-button/r-icon-button.story.js
  packages/recomponents/src/components/r-icon-button/r-icon-button.vue
  packages/recomponents/src/components/r-icon/r-icon.scss
  packages/recomponents/src/components/r-input/r-input.scss
  packages/recomponents/src/components/r-loader/r-loader.scss
  packages/recomponents/src/components/r-radio/r-toggle.scss
  packages/recomponents/src/components/r-tile/r-tile.scss
  packages/recomponents/src/directives/r-tooltip.scss
  packages/recomponents/src/styles/theme.scss
Labels: awaiting review

#32 feat(r-button): Add link option for button
  packages/recomponents/src/components/r-button/r-button.scss
  packages/recomponents/src/components/r-button/r-button.story.js
  packages/recomponents/src/components/r-button/r-button.vue
Labels: bug, chore

#34 chore(button): keep the same as the v-button in recomm
  packages/recomponents/src/components/r-button/r-button.scss
  packages/recomponents/src/components/r-button/r-button.vue
Labels: chore

#37 fix(button): Adjust the color, the same with re-ui
  packages/recomponents/src/styles/theme.scss
Labels: awaiting review, bug, chore

#39 docs(button): update doc
  packages/recomponents/src/components/r-button/r-button.md
Labels: awaiting review, chore
