Repository Rebilly/rebilly-recomponents, pull requests merged in 2019-12, with the labels that each got.

#92 Add branding to storybook
  packages/recomponents/.storybook/config.js
  packages/recomponents/.storybook/manager-head.html
  packages/recomponents/.storybook/theme.js
Labels: chore

#90 fix(all): Add polyfills support for IE 11
  packages/recomponents/package.json
  packages/recomponents/src/components/r-button/r-button.story.js
  packages/recomponents/src/index.js
  packages/recomponents/src/polyfill.js
  packages/recomponents/yarn.lock
Labels: task

#89 Fix directive registration
  package.json
  packages/recomponents/package.json
  packages/recomponents/src/common/helpers/index.js
  packages/recomponents/src/common/helpers/kebab-case.js
  packages/recomponents/src/components/r-select/r-select.spec.js
  packages/recomponents/src/directives/r-click-outside/r-click-outside.js
  packages/recomponents/src/directives/r-content/r-content.js
  packages/recomponents/src/directives/r-content/r-content.spec.js
  packages/recomponents/src/directives/r-fs-block.js
  packages/recomponents/src/directives/r-lazy.js
  packages/recomponents/src/directives/r-tooltip/r-tooltip.js
  packages/recomponents/src/index.js
Labels: bug

#94 Update r-loader styles trying to support fullscreen mode
  packages/recomponents/src/components/r-loader/__snapshots__/r-loader.spec.js.snap
  packages/recomponents/src/components/r-loader/r-loader.scss
  packages/recomponents/src/components/r-loader/r-loader.spec.js
  packages/recomponents/src/components/r-loader/r-loader.story.js
  packages/recomponents/src/components/r-loader/r-loader.vue
  packages/recomponents/src/components/r-modal/__snapshots__/r-modal.spec.js.snap
  packages/recomponents/src/styles/theme.scss
Labels: bug

#96 Add global test setup and register directives globally
  packages/recomponents/jest.config.js
  packages/recomponents/src/components/index.js
  packages/recomponents/src/components/r-select/r-select.spec.js
  packages/recomponents/src/directives/index.js
  packages/recomponents/src/directives/r-click-outside/r-click-outside.spec.js
  packages/recomponents/src/directives/r-content/r-content.spec.js
  packages/recomponents/src/directives/r-tooltip/r-tooltip.spec.js
  packages/recomponents/src/index.js
  packages/recomponents/src/setup-test.js
Labels: chore

#93 Create RAvatar component
  packages/gridsome/src/pages/Todo.vue
  packages/gridsome/yarn.lock
  packages/nuxt/components/LazyLoadingImage.vue
  packages/nuxt/components/MultiStepForm.vue
  packages/nuxt/components/Payment.vue
  packages/nuxt/components/Tabs.vue
  packages/nuxt/components/Todo.vue
  packages/nuxt/pages/index.vue
  packages/nuxt/pages/todo.vue
  packages/nuxt/yarn.lock
  packages/recomponents/.storybook/knobs.js
  packages/recomponents/src/components/index.js
  packages/recomponents/src/components/r-avatar/__snapshots__/r-avatar.spec.js.snap
  packages/recomponents/src/components/r-avatar/r-avatar.md
  packages/recomponents/src/components/r-avatar/r-avatar.scss
  packages/recomponents/src/components/r-avatar/r-avatar.spec.js
  packages/recomponents/src/components/r-avatar/r-avatar.story.js
  packages/recomponents/src/components/r-avatar/r-avatar.vue
  packages/recomponents/src/components/r-icon/r-icon.story.js
  packages/recomponents/src/styles/theme.scss
Labels: task

#97 fix(RSelect): disallow use of v-html to prevent XSS attack
  packages/recomponents/.eslintrc
  packages/recomponents/src/components/r-select/r-select.vue
Labels: bug

#98 fix(r-select): Do not toggle r-select when tag is removing
  packages/recomponents/src/components/r-select/r-select.vue
Labels: bug

#100 fix(component): Fix difference in RModal
  packages/recomponents/src/components/r-modal/__snapshots__/r-modal.spec.js.snap
  packages/recomponents/src/components/r-modal/r-modal.vue
  packages/recomponents/src/styles/theme.scss
Labels: awaiting review

#107 The issues on IE11
  packages/recomponents/src/components/r-button/r-button.scss
  packages/recomponents/src/components/r-pagination/r-pagination-control.scss
  packages/recomponents/src/components/r-popper/r-popper.scss
  packages/recomponents/src/components/r-popper/r-popper.story.js
  packages/recomponents/src/styles/theme.scss
  packages/recomponents/src/styles/typography.scss
Labels: bug

#102 feat(RDateInput): one more type called datepicker
  packages/recomponents/src/components/r-date-input/__snapshots__/r-date-input.spec.js.snap
  packages/recomponents/src/components/r-date-input/r-date-input.story.js
  packages/recomponents/src/components/r-date-input/r-date-input.vue
  packages/recomponents/yarn.lock
Labels: task

#108 fix(component): Allow on one page fullscreen loader with inline
  packages/recomponents/src/components/r-loader/r-loader.scss
  packages/recomponents/src/styles/theme.scss
  packages/recomponents/yarn.lock
Labels: bug

#109 fix(r-loader): Fix r-loader border radius for fullscreen
  packages/recomponents/src/components/r-loader/r-loader.scss
Labels: bug

#110 Split Recomponents stylesheet into main and theme
  packages/recomponents/.storybook/config.js
  packages/recomponents/.storybook/webpack.config.js
  packages/recomponents/package.json
  packages/recomponents/src/components/r-popper/r-popper.scss
  packages/recomponents/src/index.js
  packages/recomponents/src/styles/mixins.scss
  packages/recomponents/src/styles/recomm.scss
  packages/recomponents/src/styles/typography.scss
  packages/recomponents/src/styles/variables.scss
  packages/recomponents/vue.config.js
Labels: awaiting review, chore

#103 fix(RPopper): adjust the style
  packages/recomponents/src/components/r-popper/r-popper.scss
Labels: bug

#111 feat(r-img): Support aspect ratio property
  packages/recomponents/src/components/r-avatar/__snapshots__/r-avatar.spec.js.snap
  packages/recomponents/src/components/r-img/__snapshots__/r-img.spec.js.snap
  packages/recomponents/src/components/r-img/r-img.scss
  packages/recomponents/src/components/r-img/r-img.spec.js
  packages/recomponents/src/components/r-img/r-img.story.js
  packages/recomponents/src/components/r-img/r-img.vue
  packages/recomponents/src/directives/r-lazy.js
  packages/recomponents/src/stories/lazy-loading.story.js
  packages/recomponents/src/styles/recomm.scss
Labels: bug

#112 Fixed H1 Leading
  packages/recomponents/src/styles/recomm.scss
Labels: awaiting review, bug

#113 Fix Storybook in dark mode
  packages/recomponents/.storybook/manager-head.html
  packages/recomponents/.storybook/preview-head.html
  yarn.lock
Labels: bug

#114 RTabs deep links fix
  packages/nuxt/components/Tabs.vue
  packages/nuxt/layouts/default.vue
  packages/nuxt/package.json
  packages/nuxt/pages/tabs/_id.vue
  packages/nuxt/yarn.lock
  packages/recomponents/src/components/r-tabs/r-tabs.vue
Labels: bug

#115 fix(RModal): adjust the CSS
  packages/recomponents/src/components/r-modal/r-modal.scss
  packages/recomponents/src/styles/recomm.scss
Labels: bug

#106 Setup image-snapshots with addon-storyshots-puppeteer
  .dockerignore
  .travis.yml
  packages/recomponents/.dockerignore
  packages/recomponents/.gitignore
  packages/recomponents/.image-snapshots/Dockerfile
  packages/recomponents/.image-snapshots/README.md
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-avatar-all-colors-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-avatar-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-avatar-variations-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-badge-all-types-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-badge-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-button-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-button-group-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-button-size-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-button-state-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-button-type-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-checkbox-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-checkbox-multiple-checkboxes-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-date-input-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-icon-all-colors-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-icon-all-icons-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-icon-button-icon-button-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-icon-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-image-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-image-image-with-aspect-ratio-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-input-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-loader-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-loader-example-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-modal-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-modal-multi-step-form-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-pagination-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-pagination-example-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-popper-with-icon-button-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-popper-with-regular-button-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-radio-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-radio-group-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-select-async-data-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-select-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-select-object-options-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-tabs-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-tile-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-toggle-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-toggle-multiple-toggles-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-webcomponent-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-demo-lazy-loading-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-demo-payment-form-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-demo-typography-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-directives-tooltip-1-snap.png
  packages/recomponents/.image-snapshots/docker-compose.yml
  packages/recomponents/.image-snapshots/jest.config.js
  packages/recomponents/.image-snapshots/register-context.js
  packages/recomponents/.image-snapshots/storyshots-image.runner.js
  packages/recomponents/.storybook/config.js
  packages/recomponents/babel.config.js
  packages/recomponents/package.json
  packages/recomponents/yarn.lock
Labels: task

#117 Create RFileUpload component
  packages/recomponents/src/components/index.js
  packages/recomponents/src/components/r-file-upload/__snapshots__/r-file-upload.spec.js.snap
  packages/recomponents/src/components/r-file-upload/r-file-upload.md
  packages/recomponents/src/components/r-file-upload/r-file-upload.scss
  packages/recomponents/src/components/r-file-upload/r-file-upload.spec.js
  packages/recomponents/src/components/r-file-upload/r-file-upload.story.js
  packages/recomponents/src/components/r-file-upload/r-file-upload.vue
  packages/recomponents/src/components/r-img/r-img.scss
Labels: task

#119 feat(r-toast): Create RToast component
  packages/recomponents/src/components/index.js
  packages/recomponents/src/components/r-button/r-button.vue
  packages/recomponents/src/components/r-toast/__snapshots__/r-toast.spec.js.snap
  packages/recomponents/src/components/r-toast/r-toast.md
  packages/recomponents/src/components/r-toast/r-toast.scss
  packages/recomponents/src/components/r-toast/r-toast.spec.js
  packages/recomponents/src/components/r-toast/r-toast.story.js
  packages/recomponents/src/components/r-toast/r-toast.vue
  packages/recomponents/src/index.js
  packages/recomponents/src/plugins/r-toast-manager/index.js
  packages/recomponents/src/plugins/r-toast-manager/r-toast-manager.js
  packages/recomponents/src/plugins/r-toast-manager/r-toast-types.js
  packages/recomponents/src/styles/recomm.scss
Labels: awaiting review, task

#118 fix(all): fix the transition bugs and improve transition
  packages/recomponents/src/components/r-modal/__snapshots__/r-modal.spec.js.snap
  packages/recomponents/src/components/r-modal/r-modal.scss
  packages/recomponents/src/components/r-modal/r-modal.story.js
  packages/recomponents/src/components/r-modal/r-modal.vue
  packages/recomponents/src/components/r-popper/r-popper.scss
  packages/recomponents/src/components/r-popper/r-popper.story.js
  packages/recomponents/src/components/r-popper/r-popper.vue
  packages/recomponents/src/styles/animate.scss
Labels: awaiting review, task
