Repository Rebilly/rebilly-recomponents, pull requests merged in 2019-10, with the labels that each got.

#43 chore(components): Rename RDropdown to RPopper
  packages/recomponents/src/components/r-popper/__snapshots__/r-popper.spec.js.snap
  packages/recomponents/src/components/r-popper/r-popper.md
  packages/recomponents/src/components/r-popper/r-popper.scss
  packages/recomponents/src/components/r-popper/r-popper.spec.js
  packages/recomponents/src/components/r-popper/r-popper.story.js
  packages/recomponents/src/components/r-popper/r-popper.vue
  packages/recomponents/src/components/r-select/r-select.spec.js
  packages/recomponents/src/components/r-select/r-select.story.js
  packages/recomponents/src/components/r-select/r-select.vue
  packages/recomponents/src/components/r-tabs/r-tab.vue
  packages/recomponents/src/components/r-tabs/r-tabs.story.js
  packages/recomponents/src/components/r-tabs/r-tabs.vue
  packages/recomponents/src/components/r-tile/r-tile.spec.js
  packages/recomponents/src/directives/r-content/r-content.spec.js
  packages/recomponents/src/index.js
  packages/recomponents/src/mixins/async-input-mixin.js
Labels: awaiting review, chore

#49 refactor(r-modal): rename .modal to .r-modal so that no conflicts in recomm
  packages/recomponents/src/components/r-modal/__snapshots__/r-modal.spec.js.snap
  packages/recomponents/src/components/r-modal/r-modal.scss
  packages/recomponents/src/components/r-modal/r-modal.vue
Labels: awaiting review, chore

#50 fix(style): just release it as refactor can't be triggered
  packages/recomponents/package.json
Labels: chore

#52 feat(all): Add 3 features
  packages/gridsome/src/components/Payment.vue
  packages/nuxt/components/Payment.vue
  packages/recomponents/src/components/r-button-group/r-button-group.md
  packages/recomponents/src/components/r-button-group/r-button-group.spec.js
  packages/recomponents/src/components/r-button-group/r-button-group.story.js
  packages/recomponents/src/components/r-button-group/r-button-group.vue
  packages/recomponents/src/components/r-button/__snapshots__/r-button.spec.js.snap
  packages/recomponents/src/components/r-button/r-button.scss
  packages/recomponents/src/components/r-button/r-button.story.js
  packages/recomponents/src/components/r-button/r-button.vue
  packages/recomponents/src/components/r-icon/r-icon.story.js
  packages/recomponents/src/components/r-icon/r-icon.vue
  packages/recomponents/src/components/r-pagination/__snapshots__/r-pagination.spec.js.snap
  packages/recomponents/src/components/r-webcomponent/__snapshots__/r-webcomponent.spec.js.snap
  packages/recomponents/src/index.js
Labels: task

#53 fix(r-pagination): fix Infinite loop
  packages/recomponents/src/components/r-pagination/r-pagination.vue
Labels: bug

#55 Fix badge component
  packages/recomponents/src/components/r-badge/__snapshots__/r-badge.spec.js.snap
  packages/recomponents/src/components/r-badge/r-badge.md
  packages/recomponents/src/components/r-badge/r-badge.scss
  packages/recomponents/src/components/r-badge/r-badge.spec.js
  packages/recomponents/src/components/r-badge/r-badge.story.js
  packages/recomponents/src/components/r-badge/r-badge.vue
  packages/recomponents/src/styles/theme.scss
Labels: bug

#60 fix(release): trigger release by readme update
  README.md
Labels: chore
