Repository Rebilly/rebilly-recomponents, pull requests merged in 2020-03, with the labels that each got.

#162 chore(storybook): Fix table header in dark mode
  packages/recomponents/.storybook/preview-head.html
  packages/recomponents/package.json
  packages/recomponents/yarn.lock
Labels: bug, chore

#161 fix(r-popper): support the actions section in the popper
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-badge-all-types-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-button-group-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-checkbox-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-checkbox-multiple-checkboxes-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-date-range-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-file-upload-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-file-upload-with-preview-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-grid-grid-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-grid-repeater-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-icon-all-colors-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-icon-all-icons-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-image-image-with-aspect-ratio-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-input-validation-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-loader-example-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-pagination-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-pagination-custom-first-page-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-pagination-update-from-parent-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-select-async-data-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-select-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-select-object-options-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-select-validation-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-tabs-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-tile-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-toast-all-types-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-toast-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-toast-manager-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-toast-render-function-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-components-webcomponent-component-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-demo-lazy-loading-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-demo-payment-form-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-demo-typography-1-snap.png
  packages/recomponents/.image-snapshots/__image_snapshots__/storyshots-image-runner-js-rebilly-recomponents-0-0-1-directives-tooltip-1-snap.png
  packages/recomponents/src/components/r-date-range/r-date-range.spec.js
  packages/recomponents/src/components/r-date-range/r-date-range.story.js
  packages/recomponents/src/components/r-date-range/r-date-range.vue
  packages/recomponents/src/components/r-popper/r-popper.scss
  packages/recomponents/src/components/r-popper/r-popper.story.js
Labels: bug

#163 fix(r-tab): support the preselected tab
  packages/recomponents/src/components/r-tabs/r-tabs.vue
Labels: bug

#164 feat(r-grid): support international format for numeric grid type
  packages/recomponents/src/components/r-grid/columnTypes/numeric.js
  packages/recomponents/src/components/r-grid/r-grid.story.js
Labels: task

#166 chore(component): add for attribute to labels in r-input and r-select
  packages/recomponents/src/components/r-input/r-input.vue
  packages/recomponents/src/components/r-select/r-select.vue
Labels: task

#152 Use Yarn Workspaces
  .travis.yml
  README.md
  package.json
  packages/gridsome/gridsome.config.js
  packages/gridsome/package.json
  packages/gridsome/yarn.lock
  packages/nuxt/nuxt.config.js
  packages/nuxt/package.json
  packages/nuxt/yarn.lock
  packages/recomponents/package.json
  packages/recomponents/src/components/r-avatar/r-avatar.spec.js
  packages/recomponents/src/components/r-badge/r-badge.spec.js
  packages/recomponents/src/components/r-button/r-button.spec.js
  packages/recomponents/src/components/r-checkbox/r-checkbox.spec.js
  packages/recomponents/src/components/r-date-range/__snapshots__/r-date-range.spec.js.snap
  packages/recomponents/src/components/r-date-range/r-date-range.spec.js
  packages/recomponents/src/components/r-file-upload/r-file-upload.spec.js
  packages/recomponents/src/components/r-grid/r-grid.spec.js
  packages/recomponents/src/components/r-icon-button/r-icon-button.spec.js
  packages/recomponents/src/components/r-icon/r-icon.spec.js
  packages/recomponents/src/components/r-img/r-img.spec.js
  packages/recomponents/src/components/r-loader/r-loader.spec.js
  packages/recomponents/src/components/r-modal/__snapshots__/r-modal.spec.js.snap
  packages/recomponents/src/components/r-modal/r-modal.spec.js
  packages/recomponents/src/components/r-pagination-control/r-pagination-control.spec.js
  packages/recomponents/src/components/r-pagination/r-pagination.spec.js
  packages/recomponents/src/components/r-popper/r-popper.spec.js
  packages/recomponents/src/components/r-radio/r-radio.spec.js
  packages/recomponents/src/components/r-select/__snapshots__/r-select.spec.js.snap
  packages/recomponents/src/components/r-select/r-select.spec.js
  packages/recomponents/src/components/r-tabs/r-tabs.spec.js
  packages/recomponents/src/components/r-tile/r-tile.spec.js
  packages/recomponents/src/components/r-toast/r-toast.spec.js
  packages/recomponents/src/components/r-toggle/r-toggle.spec.js
  packages/recomponents/src/components/r-webcomponent/r-webcomponent.spec.js
  packages/recomponents/src/directives/r-content/r-content.spec.js
  yarn.lock
Labels: awaiting review, task

#165 feat(r-grid): check the changes before fetching data
  packages/recomponents/src/components/r-grid/__snapshots__/r-grid.spec.js.snap
  packages/recomponents/src/components/r-repeater/r-repeater.vue
Labels: task

#167 fix(master): version build fix
  packages/recomponents/package.json
Labels: bug

#168 Use Github Actions instead of Travis
  .github/workflows/recomponents.yml
  .gitignore
  .travis.yml
  packages/recomponents/package.json
  packages/recomponents/src/components/r-date-range/__snapshots__/r-date-range.spec.js.snap
  packages/recomponents/src/components/r-date-range/r-date-range.spec.js
Labels: awaiting review, task

#169 fix(tools): Run build in a sequence
  .github/workflows/recomponents.yml
  packages/recomponents/package.json
  packages/recomponents/vue.config.js
  yarn.lock
Labels: bug, in progress

#170 fix(r-tabs): detect attempts to visit the same nested route
  packages/recomponents/src/components/r-tabs/__snapshots__/r-tabs.spec.js.snap
  packages/recomponents/src/components/r-tabs/r-tabs.spec.js
  packages/recomponents/src/components/r-tabs/r-tabs.vue
Labels: bug

#171 Pass close option to RToastManager
  packages/recomponents/src/index.js
Labels: task

#172 Update closable / non-closable RToasts
  packages/recomponents/README.md
  packages/recomponents/src/components/r-toast/r-toast.md
  packages/recomponents/src/components/r-toast/r-toast.story.js
  packages/recomponents/src/index.js
Labels: awaiting review, task
