Repository Rebilly/rebilly-recomponents, pull requests merged in 2020-01, with the labels that each got.

#123 fix(RPopper): fix the transition bug
  packages/recomponents/src/components/r-popper/r-popper.scss
  packages/recomponents/src/components/r-popper/r-popper.vue
Labels: bug

#124 fix(RModal): delete appear event
  packages/recomponents/src/components/r-modal/r-modal.vue
Labels: awaiting review, bug

#125 chore(r-popper): fix disabled state in storybook demo
  packages/recomponents/src/components/r-popper/r-popper.story.js
Labels: awaiting review, bug, chore

#126 Replace background icon with RIcon
  packages/recomponents/src/components/r-select/__snapshots__/r-select.spec.js.snap
  packages/recomponents/src/components/r-select/r-select.scss
  packages/recomponents/src/components/r-select/r-select.vue
  packages/recomponents/src/styles/recomm.scss
  packages/recomponents/static/icons/caret-down.svg
Labels: bug

#127 Fix popper animation
  packages/recomponents/src/components/r-popper/r-popper.scss
  packages/recomponents/src/styles/animate.scss
Labels: bug

#131 fix(RModal): add r-no-scroll to body only the modal opens
  packages/recomponents/src/components/r-modal/r-modal.vue
Labels: awaiting review, bug

#134 Custom fonts demo
  packages/gridsome/src/layouts/Default.vue
  packages/gridsome/src/styles/gridsome.css
  packages/recomponents/src/index.js
  packages/recomponents/src/styles/recomm.scss
  packages/recomponents/src/styles/theme.scss
Labels: chore

#132 Update storybook to stable release
  packages/gridsome/package.json
  packages/gridsome/yarn.lock
  packages/nuxt/package.json
  packages/nuxt/yarn.lock
  packages/recomponents/.storybook/presets.js
  packages/recomponents/package.json
  packages/recomponents/src/components/r-button/r-button.vue
  packages/recomponents/yarn.lock
Labels: chore

#135 Add click event to r-badge
  packages/recomponents/src/components/r-badge/r-badge.spec.js
  packages/recomponents/src/components/r-badge/r-badge.vue
Labels: awaiting review

#137 fix(component): Cleanup RCheckbox styles
  packages/recomponents/.storybook/webpack.config.js
  packages/recomponents/src/components/r-checkbox/r-checkbox.scss
  packages/recomponents/src/components/r-input/r-input.scss
  packages/recomponents/src/styles/theme.scss
Labels: task

#138 fix(RToast): Fix visual scroll bug
  packages/recomponents/src/components/r-toast/r-toast.scss
Labels: awaiting review, bug

#139 Add new method on rtoast
  packages/recomponents/src/common/helpers/default-error-handler.js
  packages/recomponents/src/components/r-toast/r-toast.spec.js
  packages/recomponents/src/index.js
  packages/recomponents/src/plugins/r-toast-manager/r-toast-manager.js
Labels: awaiting review, task

#140 fix(directive): Fix position of tooltip for block elements
  packages/recomponents/src/directives/r-tooltip/r-tooltip.js
  packages/recomponents/src/directives/r-tooltip/r-tooltip.story.js
Labels: awaiting review, bug

#141 fix(r-toast): close toasts when user navigates to another story in st…
  packages/recomponents/src/components/r-toast/r-toast.story.js
Labels: awaiting review

#142 chore(r-toast): expose RToastManager and improve naming
  packages/recomponents/src/components/r-toast/r-toast.spec.js
  packages/recomponents/src/index.js
  packages/recomponents/src/plugins/r-toast-manager/index.js
  packages/recomponents/src/plugins/r-toast-manager/r-toast-manager.js
Labels: chore

#143 Update RPagination component with v-model
  packages/recomponents/.storybook/config.js
  packages/recomponents/.storybook/webpack.config.js
  packages/recomponents/package.json
  packages/recomponents/src/components/r-pagination/r-pagination.md
  packages/recomponents/src/components/r-pagination/r-pagination.story.js
  packages/recomponents/src/components/r-pagination/r-pagination.vue
  packages/recomponents/yarn.lock
Labels: task

#144 fix(r-date-range): Support date range picker, fix calendar picker
  packages/recomponents/.storybook/config.js
  packages/recomponents/src/components/r-date-input/__snapshots__/r-date-input.spec.js.snap
  packages/recomponents/src/components/r-date-input/r-calendar-manager.vue
  packages/recomponents/src/components/r-date-input/r-date-input.story.js
  packages/recomponents/src/components/r-date-input/r-date-input.vue
  packages/recomponents/src/index.js
Labels: bug

#145 fix(r-select): Support tag validation
  packages/recomponents/src/components/r-select/r-select.md
  packages/recomponents/src/components/r-select/r-select.story.js
  packages/recomponents/src/components/r-select/r-select.vue
Labels: awaiting review, bug

#147 feat(component): Add render function support for RToast
  packages/recomponents/src/components/r-toast/__snapshots__/r-toast.spec.js.snap
  packages/recomponents/src/components/r-toast/r-toast.story.js
  packages/recomponents/src/components/r-toast/r-toast.vue
Labels: task

#146 chore(storybook): Add 2 stories for Vuelidate
  packages/recomponents/package.json
  packages/recomponents/src/components/r-input/r-input.story.js
  packages/recomponents/src/components/r-select/r-select.story.js
  packages/recomponents/yarn.lock
Labels: chore

#148 fix(r-pagination): Double requests on pagination init
  packages/recomponents/src/components/r-pagination/r-pagination.story.js
  packages/recomponents/src/components/r-pagination/r-pagination.vue
Labels: bug

#149 chore(storybook): Create shared validation mock for knobs
  packages/recomponents/.storybook/knobs.js
  packages/recomponents/src/components/r-input/r-input.story.js
  packages/recomponents/src/components/r-select/r-select.story.js
Labels: bug

#150 fix(component): Fix RPagination if no pages passed
  packages/recomponents/src/components/r-pagination/r-pagination.vue
Labels: bug
