Repository Rebilly/rebilly-recomponents, pull requests merged in 2020-02, with the labels that each got.

#151 fix(r-pagination): wrong quantity of visible buttons
  packages/recomponents/src/components/r-pagination-control/r-pagination-control.vue
  packages/recomponents/src/components/r-pagination/r-pagination.spec.js
  packages/recomponents/src/components/r-pagination/r-pagination.vue
Labels: bug

#153 fix(r-popper): fix view of more than 16 options in popper menu
  packages/recomponents/src/components/r-popper/r-popper.scss
  packages/recomponents/src/components/r-popper/r-popper.story.js
Labels: bug

#155 fix(r-tabs): update the style
  packages/recomponents/src/styles/theme.scss
Labels: awaiting review, bug

#157 fix(r-popper): hide scrollbar
  packages/recomponents/src/components/r-popper/r-popper.scss
  packages/recomponents/src/components/r-popper/r-popper.story.js
Labels: bug

#158 Implement RDateRange component
  packages/recomponents/.storybook/config.js
  packages/recomponents/src/common/helpers/format-date.js
  packages/recomponents/src/common/helpers/index.js
  packages/recomponents/src/components/index.js
  packages/recomponents/src/components/r-button-group/r-button-group.scss
  packages/recomponents/src/components/r-date-input/__snapshots__/r-date-input.spec.js.snap
  packages/recomponents/src/components/r-date-input/r-calendar-manager.spec.js
  packages/recomponents/src/components/r-date-input/r-calendar-manager.vue
  packages/recomponents/src/components/r-date-input/r-date-input.spec.js
  packages/recomponents/src/components/r-date-input/r-date-input.story.js
  packages/recomponents/src/components/r-date-input/r-date-input.vue
  packages/recomponents/src/components/r-date-range/__snapshots__/r-date-range.spec.js.snap
  packages/recomponents/src/components/r-date-range/calendar-presets.js
  packages/recomponents/src/components/r-date-range/r-date-range.md
  packages/recomponents/src/components/r-date-range/r-date-range.scss
  packages/recomponents/src/components/r-date-range/r-date-range.spec.js
  packages/recomponents/src/components/r-date-range/r-date-range.story.js
  packages/recomponents/src/components/r-date-range/r-date-range.vue
Labels: task

#160 fix(component): Fix RButtonGroup items in Safari
  packages/recomponents/src/components/r-button-group/r-button-group.scss
Labels: bug

#159 fix(r-date-range): small changes and fixies for report integration
  packages/recomponents/src/components/r-date-range/r-date-range.story.js
  packages/recomponents/src/components/r-date-range/r-date-range.vue
  packages/recomponents/src/components/r-grid/r-grid.md
  packages/recomponents/src/components/r-grid/r-grid.story.js
  packages/recomponents/src/components/r-grid/r-grid.vue
  packages/recomponents/src/components/r-repeater/r-repeater.md
  packages/recomponents/src/components/r-repeater/r-repeater.vue
Labels: bug
