Repository Rebilly/rebilly-recomponents, pull requests merged in 2020-05, with the labels that each got.

#180 Avoid infinite loop in RInput unit tests
  packages/recomponents/src/components/r-input/r-input.spec.js
  packages/recomponents/src/components/r-input/r-input.vue
Labels: awaiting review, chore

#181 fix(modal-title): Fix text transform
  packages/recomponents/src/components/r-modal/r-modal.scss
Labels: bug

#184 fix(r-grid): support frozen column, and small improvements
  packages/recomponents/src/components/r-grid/columnTypes/numeric.js
  packages/recomponents/src/components/r-grid/r-grid.scss
  packages/recomponents/src/components/r-grid/r-grid.story.js
  packages/recomponents/src/components/r-grid/r-grid.vue
  packages/recomponents/src/components/r-repeater/r-repeater.vue
  packages/recomponents/src/styles/theme.scss
Labels: task

#185 fix(r-button): capitalize only the first letter v2
  packages/recomponents/src/components/r-button/__snapshots__/r-button.spec.js.snap
  packages/recomponents/src/components/r-button/r-button.scss
  packages/recomponents/src/components/r-button/r-button.story.js
  packages/recomponents/src/components/r-button/r-button.vue
  packages/recomponents/src/components/r-date-range/__snapshots__/r-date-range.spec.js.snap
  packages/recomponents/src/components/r-icon-button/__snapshots__/r-icon-button.spec.js.snap
  packages/recomponents/src/components/r-icon-button/r-icon-button.story.js
  packages/recomponents/src/components/r-icon-button/r-icon-button.vue
  packages/recomponents/src/components/r-pagination-control/__snapshots__/r-pagination-control.spec.js.snap
  packages/recomponents/src/components/r-pagination/__snapshots__/r-pagination.spec.js.snap
  packages/recomponents/src/components/r-webcomponent/__snapshots__/r-webcomponent.spec.js.snap
  packages/recomponents/src/styles/helpers.scss
Labels: bug

#186 Hot fix for width of r-grid with frozen column
  packages/recomponents/src/components/r-grid/r-grid.scss
Labels: bug

#188 Make buttons with capitalized text accesible
  packages/recomponents/src/components/r-button/__snapshots__/r-button.spec.js.snap
  packages/recomponents/src/components/r-button/r-button.vue
  packages/recomponents/src/components/r-date-range/__snapshots__/r-date-range.spec.js.snap
  packages/recomponents/src/components/r-icon-button/__snapshots__/r-icon-button.spec.js.snap
  packages/recomponents/src/components/r-icon-button/r-icon-button.vue
  packages/recomponents/src/components/r-pagination-control/__snapshots__/r-pagination-control.spec.js.snap
  packages/recomponents/src/components/r-pagination/__snapshots__/r-pagination.spec.js.snap
  packages/recomponents/src/components/r-webcomponent/__snapshots__/r-webcomponent.spec.js.snap
Labels: chore

#189 fix(r-grid): fix date column timezone issue
  packages/recomponents/src/components/r-grid/columnTypes/date.js
Labels: bug

#191 fix(r-grid): make numeric columns formatted and hide scrollbars
  packages/recomponents/src/components/r-grid/r-grid.scss
Labels: bug
